apiVersion: v1
kind: Service
metadata:
  name: registry-docker-registry-nodeport
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - port: 30000
      targetPort: 5000
      nodePort: 30000
